### ISSUE TITLE
Unhandled exception if interpreter is not set

### ISSUE THREAD

**Issue by poxip** [Xion/gisht#1]
If gist doesn't define which interpreter should be used (eg., `#!/bin/sh`) it causes __OSError__ while gisht's trying to run the script, for example:
```traceback
$ gisht poxip/gisht-issue-0.py
Traceback (most recent call last):
  File "/usr/local/gisht/bin/gisht", line 9, in <module>
    load_entry_point('gisht==0.3', 'console_scripts', 'gisht')()
  File "/usr/local/gisht/local/lib/python2.7/site-packages/gisht/__main__.py", line 61, in main
    run_gist(gist, gist_args)
  File "/usr/local/gisht/local/lib/python2.7/site-packages/gisht/gists.py", line 42, in run_gist
    os.execv(cmd, [cmd] + list(args))
OSError: [Errno 8] Exec format error
```
__Ideas:__
* if file's mimetype exists (like `type: "application/x-python"`) use proper interpreter

otherwise
* try to detect the language (and the interpreter then)
  * if cannot, inform about that.

**Comment by Xion** [comment]
This has been fixed in 0.4.
